//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chi_tiet_lop_hoc
    {
        public int id { get; set; }
        public Nullable<int> ma_lop { get; set; }
        public string ma_hs { get; set; }
    
        public virtual hoc_sinh hoc_sinh { get; set; }
        public virtual lop_hoc lop_hoc { get; set; }
    }
}
