//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoLienLacDienTuEntities : DbContext
    {
        public SoLienLacDienTuEntities()
            : base("name=SoLienLacDienTuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bao_cao> bao_cao { get; set; }
        public virtual DbSet<chi_tiet_lop_hoc> chi_tiet_lop_hoc { get; set; }
        public virtual DbSet<diem_kt> diem_kt { get; set; }
        public virtual DbSet<giao_vien> giao_vien { get; set; }
        public virtual DbSet<hanh_kiem> hanh_kiem { get; set; }
        public virtual DbSet<hoc_ki> hoc_ki { get; set; }
        public virtual DbSet<hoc_sinh> hoc_sinh { get; set; }
        public virtual DbSet<lop_hoc> lop_hoc { get; set; }
        public virtual DbSet<mon_hoc> mon_hoc { get; set; }
        public virtual DbSet<nam_hoc> nam_hoc { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<thoi_khoa_bieu> thoi_khoa_bieu { get; set; }
    }
}
