//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class diem_kt
    {
        public string ma_hs { get; set; }
        public Nullable<double> diem { get; set; }
        public int loai { get; set; }
        public int ma_mon { get; set; }
        public Nullable<int> ma_hoc_ki { get; set; }
        public Nullable<int> ma_nam { get; set; }
    
        public virtual hoc_ki hoc_ki { get; set; }
        public virtual hoc_sinh hoc_sinh { get; set; }
        public virtual mon_hoc mon_hoc { get; set; }
        public virtual nam_hoc nam_hoc { get; set; }
    }
}
