//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoc_sinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hoc_sinh()
        {
            this.bao_cao = new HashSet<bao_cao>();
            this.diem_kt = new HashSet<diem_kt>();
            this.lop_hoc = new HashSet<lop_hoc>();
        }
    
        public string ma_hs { get; set; }
        public string pass { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<byte> gioiTinh { get; set; }
        public Nullable<int> khoa { get; set; }
        public string sdt { get; set; }
        public string trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bao_cao> bao_cao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diem_kt> diem_kt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lop_hoc> lop_hoc { get; set; }
    }
}
