//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class lop_hoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lop_hoc()
        {
            this.chi_tiet_lop_hoc = new HashSet<chi_tiet_lop_hoc>();
            this.thoi_khoa_bieu = new HashSet<thoi_khoa_bieu>();
        }
    
        public int ma_lop { get; set; }
        public string ten { get; set; }
        public string ma_gv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_lop_hoc> chi_tiet_lop_hoc { get; set; }
        public virtual giao_vien giao_vien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thoi_khoa_bieu> thoi_khoa_bieu { get; set; }
    }
}
